files:
  - source: /NotepadImproved/EditorMain.resx
    translation: /NotepadImproved/EditorMain.%locale%.resx
  - source: /NotepadImproved/Main.resx
    translation: /NotepadImproved/Main.%locale%.resx
